TerrainHRM/Controllers/HrmInitialController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using TerrainHRM.DTOs;
using TerrainHRM.Helper;
using TerrainHRM.Interfaces;
using TerrainHRM.Models;

namespace TerrainHRM.Controllers
{
    public class HrmInitialController : Controller
    {
        private readonly IDivisionMstRepository _division;
        private readonly IDeptRepository _dept;
        private readonly ISectRepository _sect;
        public HrmInitialController(IDivisionMstRepository division, IDeptRepository dept, ISectRepository sect)
        {
            _division = division;
            _dept = dept;
            _sect = sect;
        }
        public IActionResult Index()
        {
            var divisionList = _division.GetDivisionList();
            return View("Division",divisionList);
        }

        #region Create Division
        [HttpGet]
        public IActionResult CreateUpdateDivision(int id = 0)
        {            
            var divDto = new DivisionMstDto();
            if (id>0)
            {
                var div = _division.GetDivisionById(id);
                divDto.Division = div;

                var deptList = _dept.DeptListByDivision(id)
                    .OrderBy(x=>x.DeptOrder).ToList();
                if (deptList.Count==0)
                {
                    deptList.Add(new DeptMst
                    {
                        Id = 0
                    });
                }

                if (deptList.Count>0)
                {
                    var sectDeptId = deptList.FirstOrDefault().Id;
                    var sectList = _sect.GetListEntity().Where(s => s.SectDeptId == sectDeptId)
                        .OrderBy(x => x.SectOrder)
                        .ToList();
                    if (sectList.Count>0)
                    {
                        divDto.Sections.AddRange(sectList);
                    }
                    else
                    {
                        divDto.Sections.Add(new SectionMst()
                        {
                            Id = 0
                        });
                    }
                }
                else
                {
                    divDto.Sections.Add(new SectionMst()
                    {
                        Id = 0
                    });
                }

                divDto.Departments.AddRange(deptList);
            }
            else
            {
                var div = new DivisionMst();
                var dept = new DeptMst()
                {
                    Id = 0
                };
                divDto.Division = div;
                divDto.Departments.Add(dept);
            }

            return View(divDto);
        }

        [HttpPost]
        public IActionResult CreateUpdateDivision(DivisionMstDto divisionMstDto)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var resutl = _division.CreateUpdateDivision(divisionMstDto.Division);
                    #region department
                    if (resutl>0)
                    {
                        var deptId = DbConnectionHelper.GetGeneratedPK("DEPT_MST", "DEPT_ID") + 1;
                        var insertDeptList = new List<DeptMst>();
                        var updateDeptList = new List<DeptMst>();
                        foreach (var department in divisionMstDto.Departments)
                        {
                            if (department.Id == 0)
                            {
                                department.Id = deptId;
                                department.DeptDivmId = resutl;
                                ++deptId;
                                insertDeptList.Add(department);
                            }
                            else
                            {
                                department.DeptDivmId = resutl;
                                updateDeptList.Add(department);
                            }
                        }

                        if (insertDeptList.Count>0)
                        {
                            _dept.CreatNewEntity(insertDeptList);
                        }

                        if (updateDeptList.Count>0)
                        {
                            _dept.UpdateEntity(updateDeptList);
                        }

                        var sectId = DbConnectionHelper.GetGeneratedPK("SECTION_MST", "SECT_ID")+1;
                        var sectInsertList = new List<SectionMst>();
                        var sectUpdateList = new List<SectionMst>();
                        foreach (var section in divisionMstDto.Sections)
                        {
                            if (section.Id>0)
                            {
                                sectUpdateList.Add(section);
                            }
                            else
                            {
                                section.Id = sectId;
                                ++sectId;
                                sectInsertList.Add(section);
                            }

                            if (sectInsertList.Count>0)
                            {
                                _sect.CreatNewEntity(sectInsertList);
                            }

                            if (sectUpdateList.Count>0)
                            {
                                _sect.UpdateEntity(sectUpdateList);
                            }

                        }
                        
                    }
                    #endregion department
                    if (resutl>0)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        var error = new Errors();
                        error.ErrorMessage = "Data could not be inserted";
                        error.ErrorEvent = "CreateUpdateDivision in HrmInitial";
                        error.ErrorStackTrace = "";
                        return RedirectToAction("Index", "AllErrors", error);
                    }
                }
                catch(Exception e)
                {
                    var error = new Errors();
                    error.ErrorMessage = e.Message;
                    error.ErrorEvent = "CreateUpdateDivision in HrmInitial";
                    error.ErrorStackTrace = e.StackTrace;
                    error.ErrorInnerMessage = e.InnerException.Message;
                    return RedirectToAction("Index", "AllErrors", error);
                }
            }
            else
            {
                var error = new Errors();
                error.ErrorMessage = "Model State is not valid.";
                error.ErrorEvent = "CreateUpdateDivision in HrmInitial";
                error.ErrorStackTrace = "";
                return RedirectToAction("Index", "AllErrors", error);
            }

            
        }

        [HttpGet]
        public List<SectionMst> GetSections(int deptId)
        {
            var sectionList = _sect.SectionListByDept(deptId);
            return sectionList;
        }
        #endregion Create Division
    }
}

TerrainHRM/Views/HrmInitial/CreateUpdateDivision.cshtml
@model TerrainHRM.DTOs.DivisionMstDto
@{
    ViewData["Title"] = "Division List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/css/division.css" rel="stylesheet" />

<div class="row" style="padding-top:10px;">
    <div class="col-6 text-left">
        <h4>Create New Division</h4>
    </div>
    <div class="col-6 text-right">
        <a class="btn btn-primary" asp-action="CreateUpdateDivision" asp-controller="HrmInitial">Clear Page</a>
    </div>
</div>
<hr />


<div class="main-div">
    <div class="division-div">
        <div class="division-container">
            <input type="hidden" name="DeptId" id="DeptId" value="" />
            <form action="CreateUpdateDivision" method="post">
                <div class="row">
                    <div class="col-2">

                    </div>
                    <div class="col-8">
                        <div class="row">
                            <div class="col-3">
                                    <input asp-for="Division.DivmId" hidden />
                                <div class="form-group">
                                    <label asp-for="Division.DivmCode"></label>
                                    <input style="width:150px!important;" asp-for="Division.DivmCode" class="form-control" />
                                </div>
                            </div>
                            <div class="col-5">
                                <div class="form-group">
                                    <label asp-for="Division.DivmName"></label>
                                    <input asp-for="Division.DivmName" class="form-control" />
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <label asp-for="Division.DivmNameBn"></label>
                                    <input asp-for="Division.DivmNameBn" class="form-control" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-2">

                    </div>
                </div>
                <div class="row">
                    <div class="col-6 department-container" id="department-container">
                        <fieldset>
                            <legend style="color:black;font-weight:bold; font-size:14px;">Departments</legend>
                        </fieldset>
                        <div style="height:350px!important;overflow-y:scroll">

                            <table class="table table-bordered table-sm mx-auto">
                                <thead class="thead-dark sticky-top">
                                    <tr>
                                        <th>Order</th>
                                        <th>Department Name</th>
                                        <th>Department Name Bangla</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @for (int i = 0; i < Model.Departments.Count; i++)
                                    {
                                        <tr>
                                            <td hidden>
                                                <input asp-for="Departments[i].Id" hidden />
                                            </td>
                                            <td>
                                                <input style="width:50px!important;" asp-for="Departments[i].DeptOrder" class="form-control" />
                                            </td>
                                            <td>
                                                <input asp-for="Departments[i].DeptName" class="form-control" />
                                            </td>
                                            <td>
                                                <input asp-for="Departments[i].DeptNameBn" class="form-control" />
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <input id="department-add" style="float:right; margin-right:10px;" type="button" class="btn btn-primary" value="Add" />
                    </div>
                    <div class="col-6 section-container" id="section-container">
                        <fieldset>
                            <legend style="color:black;font-weight:bold; font-size:14px;">Sections</legend>
                        </fieldset>
                        <div style="height:350px!important; overflow-y:scroll;">
                            <table class="table table-bordered table-sm mx-auto">
                                <thead class="thead-dark sticky-top">
                                    <tr>
                                        <th>Order</th>
                                        <th>Section Name</th>
                                        <th>Bangla Name</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @for (int j = 0; j < Model.Sections.Count; j++)
                                    {
                                        <tr>
                                            <td hidden>
                                                <input hidden asp-for="Sections[j].Id" />
                                            </td>
                                            <td hidden>
                                                <input hidden asp-for="Sections[j].SectDeptId" class="sect-dept-id" />
                                            </td>
                                            <td>
                                                <input style="width:50px!important;" asp-for="Sections[j].SectOrder" class="form-control" />
                                            </td>
                                            <td>
                                                <input asp-for="Sections[j].SectName" class="form-control" />
                                            </td>
                                            <td>
                                                <input asp-for="Sections[j].SectNameBn" class="form-control" />
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <div class="form-group">
                            <a class="btn btn-warning" asp-controller="HrmInitial" asp-action="Index">Cancel</a>
                            <input style="float:right;" type="submit" value="Submit" class=" btn btn-success" />
                            <input id="section-add" style="float:right; margin-right:10px;" type="button" class="btn btn-primary" value="Add" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


@*<script src="~/js/hrmInitial.js"></script>*@
<script type="text/javascript">
    const addBtn = document.getElementById('department-add');
    const addSectBtn = document.getElementById('section-add');


    const deptTable = document.getElementById('department-container')
        .getElementsByTagName('table')[0];

    var deptRows = deptTable.rows;

    for (let i = 0; i < deptRows.length; i++) {
        deptRows[i].addEventListener('click', function () {
            let deptTd = this.getElementsByTagName('td')[0];
            let deptId = deptTd.getElementsByTagName('input')[0].value;
            console.log(deptId);
            let sectionData = getSections(deptId);
            console.log(sectionData);
        });
    }

    


    function addRowToTable(pName) {
        const divEl = document.getElementById(pName);
        let elTable = divEl.getElementsByTagName('table')[0];
        let elTableRows = elTable.rows;
        var rowLenth = elTableRows.length;
        let rowOuterHtml = elTableRows[elTableRows.length - 1].outerHTML;
        rowOuterHtml = rowOuterHtml.replaceAll('_' + Number(rowLenth - 2) + '_', '_' + Number(rowLenth - 1) + '_');
        rowOuterHtml = rowOuterHtml.replaceAll('[' + Number(rowLenth - 2) + '].', '[' + Number(rowLenth - 1) + '].');
        let newRow = elTable.insertRow();
        newRow.innerHTML = rowOuterHtml;
    }



    function ClearCreatedRow(pName) {
        const targetedDiv = document.getElementById(pName);
        let table = targetedDiv.getElementsByClassName("table")[0];
        let rows = table.rows;
        var lastRow = rows[rows.length - 1];
        var tableTd = lastRow.getElementsByTagName("td");
        var tdLength = tableTd.length;

        for (var i = 0; i < tableTd.length; i++) {
            var lastChildofTd = tableTd[i].getElementsByTagName("input")[0];
            if (i === 0) {
                lastChildofTd.value = "0";
            } else {
                lastChildofTd.value = "";
            }
        }
    }

    function populateSections(pData) {

        const targetedDiv = document.getElementById('section-container');
        let table = targetedDiv.getElementsByClassName("table")[0];
        let rows = table.rows;

        for (var j = 0; j < rows.length; j++) {
            var currRow = rows[j];
            
            var tableTd = currRow.getElementsByTagName("td");

            for (var i = 0; i < tableTd.length; i++) {
                var lastChildofTd = tableTd[i].getElementsByTagName("input")[0];
                lastChildofTd.value = pData[i];
            }
        }

    }

        //var sectionList;
        //getSections(1).then(function (data) {
        //    sectionList = data;
        //    console.log(sectionList);
        //});

    function getSections(id) {
        if (id) {
           return $.ajax({
                type: "GET",
                url: "/HrmInitial/GetSections",
                data: { deptId: id },
                success: function (res) {
                    //console.log(res);
                   // var sectionList = res;
                },
                error: function (err) {
                    console.log(err);
                }
            })
        }
    }

    //function addRowToTable(pName) {
    //    const divEl = document.getElementById(pName);
    //    let elTable = divEl.getElementsByTagName('table')[0];
    //    let elTableRows = elTable.rows;
    //    var rowLenth = elTableRows.length;
    //    let rowOuterHtml = elTableRows[elTableRows.length - 1].outerHTML;
    //    rowOuterHtml = rowOuterHtml.replaceAll('_' + Number(rowLenth - 2) + '_', '_' + Number(rowLenth - 1) + '_');
    //    rowOuterHtml = rowOuterHtml.replaceAll('[' + Number(rowLenth - 2) + '].', '[' + Number(rowLenth - 1) + '].');
    //    let newRow = elTable.insertRow();
    //    newRow.innerHTML = rowOuterHtml;
    //    ClearCreatedRow(pName);
    //}

    //function ClearCreatedRow(pName) {
    //    const targetedDiv = document.getElementById(pName);
    //    let table = targetedDiv.getElementsByClassName("table")[0];
    //    let rows = table.rows;
    //    var lastRow = rows[rows.length - 1];
    //    var tableTd = lastRow.getElementsByTagName("td");

    //    for (var i = 0; i < tableTd.length - 1; i++) {
    //        var lastChildofTd = tableTd[i].getElementsByTagName("input")[0];
    //        if (i === 0) {
    //            lastChildofTd.value = "0";
    //        } else {
    //            lastChildofTd.value = "";
    //        }
    //    }
    //}

    addBtn.addEventListener('click', function () {
        addRowToTable('department-container');
        ClearCreatedRow('department-container');
    });

    addSectBtn.addEventListener('click', function () {
        addRowToTable('section-container');
        ClearCreatedRow('section-container');
    });

</script>

TerrainHRM/Views/HrmInitial/Division.cshtml
@model IEnumerable<TerrainHRM.Models.DivisionMst>
@{
    ViewData["Title"] = "Division List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row"  style="padding-top:10px;">
    <div class="col-6 text-left">
        <h4>Division List</h4>
    </div>
    <div class="col-6 text-right">
        <a class="btn btn-primary" asp-controller="HrmInitial" asp-action="CreateUpdateDivision">Create Division</a>
    </div>
</div>
<hr />
@if (Model.Count() == 0)
{
    <p>No Data Found.</p>
}
else
{
    <table class="table table-bordered col-8 table-sm mx-auto">
        <thead class="thead-dark">
            <tr>
                <th class="text-center">#</th>
                <th class="text-center">Short Name</th>
                <th class="text-center">Name</th>
                <th class="text-center">Bangla Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var divm in Model)
            {
                <tr>
                    <td class="text-center"><a asp-controller="HrmInitial" asp-action="CreateUpdateDivision" asp-route-id="@divm.DivmId"><i class="fas fa-edit"></i></a></td>
                    <td class="text-center">@divm.DivmCode</td>
                    <td class="text-center">@divm.DivmName</td>
                    <td class="text-center">@divm.DivmNameBn</td>
                </tr>
            }
        </tbody>
    </table>
}