TerrainHRM/Controllers/CompanyNewController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using TerrainHRM.DTOs;
using TerrainHRM.Helper;
using TerrainHRM.Interfaces;
using TerrainHRM.Models;

namespace TerrainHRM.Controllers
{
    public class CompanyNewController : Controller
    {
        private readonly ICompanyRepository _company;
        public CompanyNewController(ICompanyRepository company)
        {
            _company = company;
        }

        public IActionResult Index()
        {
            var companyList = _company.GetCompanyList();
            return View(companyList);
        }

        public IActionResult CompanyDetails(int id)
        {
            var company = _company.GetCompanyById(id);


            //var company = companies.Where(x => x.CimId == 1).FirstOrDefault();
            if (company != null)
            {
                ViewBag.ImagePath = company.CimFileName;
            }
            else
            {
                ViewBag.ImagePath = "";
            }
            return View(company);
        }

        public IActionResult CreateNewCompany()
        {
            var company = new HrCompanyDto();

            company.CompanyDtlList = new List<CompanyInfoDtl>() { new CompanyInfoDtl { CidId = 1 } };
            company.CompanyOffices = new List<CompanyOfficeAddress>()
            {
                new CompanyOfficeAddress{CoaId = 1}
            };

            return View(company);
        }

        [HttpPost]
        public IActionResult CreateNewCompany(CompanyInfoMst company, List<CompanyInfoDtl> companyDtls)
        {
            if (company.CimName == null)
            {
                var companyNew = new HrCompanyDto();

                companyNew.CompanyDtlList = new List<CompanyInfoDtl>() { new CompanyInfoDtl { CidId = 1 } };
                ViewBag.errorMessage = "Company Name or Company details cannot be null";
                return View(companyNew);
            }

            if (ModelState.IsValid)
            {

                //company.CimId = maxCimId;
                var result = _company.CreateNewCompany(company, companyDtls);
                if (result > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }

            }
            else
            {
                return View();
            }

            //return RedirectToAction(nameof(Index));
        }

        public IActionResult EditCompanyInfo(CompanyInfoMst company)
        {
            if (ModelState.IsValid)
            {
                var result = _company.EditCompany(company);
                if (result > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        public IActionResult DeleteCompany(int id)
        {
            var result = _company.DeleteCompany(id);
            if (result > 0)
            {
                ViewBag.DeleteAlert("Data Deleted Successfully!");
            }
            return RedirectToAction(nameof(Index));
        }


        public int InsertUpdateCompanyOffice(List<CompanyOfficeAddress> companyOffices)
        {
            List<CompanyOfficeAddress> officeToInsert = new List<CompanyOfficeAddress>();
            List<CompanyOfficeAddress> officeToUpdate = new List<CompanyOfficeAddress>();
            foreach (var office in companyOffices)
            {
                if (office.CoaId > 0)
                {
                    officeToUpdate.Add(office);
                }
                else
                {
                    officeToInsert.Add(office);
                }
            }
            int result = 0;
            if (officeToInsert.Count > 0)
            {
                var insertResult = _company.CreateCompanyOffice(officeToInsert);
                result = result + insertResult;
            }

            if (officeToUpdate.Count > 0)
            {
                var updateResult = _company.UpdateCompanyOffice(officeToUpdate);
                result = result + updateResult
;
            }

            return result;
        }


        public int DeleteCompanyOffice(int id)
        {
            var officeDeleted = _company.DeleteCompanyOffice(id);
            return officeDeleted;
        }

        [HttpGet]
        public IActionResult CreateUpdateCompanyInfo()
        {
            var company = _company.GetCompanyWithOffices();
            if (company.CimId==1)
            {
                return View(company);
            }
            else
            {
                company = new HrCompanyDto();
                company.CompanyDtlList = new List<CompanyInfoDtl>()
                    {
                        new CompanyInfoDtl(){CidId = 0}
                    };

                        company.CompanyOffices = new List<CompanyOfficeAddress>()
                    {
                        new CompanyOfficeAddress(){CoaId = 0}
                    };
            }

            return View(company);
        }

        [HttpPost]
        public IActionResult CreateUpdateCompanyInfo(CompanyInfoMst company, List<CompanyInfoDtl> companyDtl, List<CompanyOfficeAddress> offices)
        {
            var companyDto = new HrCompanyDto();
            //try
            //{
                companyDto = _company.CreateComapnyOffice(company, companyDtl, offices);
            //}
           // catch(Exception e)
           // {
             //   var message = e.Message;
              //  throw new Exception("Unauthorized Error Occurred.");
            //}
            return View(companyDto);
        }
    }
}

TerrainHRM/Views/CompanyNew/CompanyDetails.cshtml
@model TerrainHRM.Models.CompanyInfoMst

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Company Details";
    var imgSrc = "~/images/" + ViewBag.ImagePath;
}



<div class="text-info row">
    <div class="text-info col-6">
        <h4>Company Information</h4>
    </div>
    <div class="text-info col-6 text-right">
        @if (Model == null)
        {
            <a class="btn btn-primary" asp-action="CreateCompany" asp-controller="Company">Create New</a>
        }
        else
        {
            <a class="btn btn-primary" asp-action="EditCompany" asp-controller="CompanyNew">Edit Company Information</a>
        }
    </div>
</div>
<hr />

<div class="row">
    <div class="col-md-6">
        @if (Model == null)
        {
            <p>No Data Found.</p>
        }
        else
        {
            <div class="form-group row">
                <div class="col-md-12 text-right">

                    <div class="form-group row" style="display:none">
                        <div class="col-2 text-right">
                            <label class="text-info">Company Id</label>
                        </div>
                        <div class="col-4">
                            @*<input class="form-control" asp-for="@Model.CimId" />*@
                            <input readonly type="text" name="id" placeholder="1,2,3" autocomplete="off" value="@Model.CimId" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2 text-right">
                            <label class="text-md-left" style="width:inherit;">Name</label>
                        </div>
                        <input readonly type="text" name="compnayName" autocomplete="off" value="@Model.CimName" class="col-md-4" />

                        <div class="col-md-2 text-right">
                            <label class="text-md-left" style="width:inherit;">Short Name</label>
                        </div>

                        <input readonly value="@Model.CimShortName" type="text" name="shortName" autocomplete="off" class="col-md-4" />
                    </div>
                    <div class="form-group row">
                        <div class="col-2 text-right">
                            <label class="text-md-left" style="width:inherit;">Address</label>
                        </div>
                        <input readonly value="@Model.CimDetails" type="text" name="details" autocomplete="off" class="col-md-4" />
                        <div class="col-2 text-right">
                            <label class="text-md-left" style="width:inherit;">Moto</label>
                        </div>
                        <input readonly value="@Model.CimMoto" type="text" name="moto" autocomplete="off" class="col-md-4" />
                    </div>
                </div>
            </div>

            <div class="col-4">
                <img src="@imgSrc" height="250" width="250" asp-append-version="true" />
            </div>
            <div class="col-md-12">
                <table class="table table-bordered table-sm mx-auto" id="company-table-01">
                    <thead class="thead-dark">
                        <tr>
                            <th>Name</th>
                            <th>Short Name</th>
                            <th>Address</th>
                            <th>Moto</th>
                        </tr>
                    </thead>
                    <tbody id="table-body-01">
                        @foreach (var item in Model.CompanyInfoDtl)
                        {
                        <tr>
                            <td>@item.CidName</td>
                            <td>@item.CidShortName</td>
                            <td>@item.CidDetails</td>
                            <td>@item.CidMoto</td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>

        }

    </div>

    <div class="col-md-6">

    </div>

</div>

TerrainHRM/Views/CompanyNew/Index.cshtml
@model IEnumerable<TerrainHRM.Models.CompanyInfoMst>

@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Company List";
}

<div class="row">
    <div class="col-6 text-lg-left">
        <h4>Company List</h4>
    </div>
    <div class="col-6 text-right">
        <a asp-controller="CompanyNew" asp-action="CreateNewCompany" class="btn btn-primary">Create New Company</a>
    </div>
</div>
<hr />
<table class="table table-bordered col-8 table-sm mx-auto">
    <thead class="thead-dark">
        <tr>
            <th>Company Name</th>
            <th>Short Name</th>
            <th>Address</th>
            <th>Moto</th>
            <th>#</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @item.CimName
            </td>
            <td>
                @item.CimShortName
            </td>
            <td>
                @item.CimDetails
            </td>
            <td>
                @item.CimMoto
            </td>
            <td>
                <a class="btn btn-primary btn-sm" asp-controller="CompanyNew" asp-action="CompanyDetails" asp-route-id="@item.CimId"><i class="fas fa-edit"></i></a>
                <a class="btn btn-primary btn-sm" asp-controller="CompanyNew" asp-action="CreateNewCompany" asp-route-id="@item.CimId"><i class="fa fa-trash" aria-hidden="true"></i></a>
            </td>
        </tr>
        }
    </tbody>
</table>