TerrainHRM/Controllers/CompanyController.cs
using System;
using System.Buffers.Text;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TerrainHRM.DTOs;
using TerrainHRM.Interfaces;
using TerrainHRM.Models;

namespace TerrainHRM.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyRepositoryOld _company;
        private readonly IWebHostEnvironment _env;
        private readonly string _rootDir;
        public CompanyController(ICompanyRepositoryOld company, IWebHostEnvironment env)
        {
            _company = company;
            _env = env;
            _rootDir = Path.Combine(_env.WebRootPath, "images");
        }
        [HttpGet]
        public IActionResult Index()
        {
            var company = _company.GetCompany();
            //var company = companies.Where(x => x.CimId == 1).FirstOrDefault();
            if (company!=null)
            {
                ViewBag.ImagePath = company.FileName;
            }else
            {
                ViewBag.ImagePath = "";
            }
            //Path.Combine(_env.WebRootPath,"images", company.FileName);
            //var employees = _company.GetEmployees();
            return View(company);
        }

        [HttpGet]
        public IActionResult CreateCompany()
        {
            var company = new HrCompany();
            return View();
        }

        [HttpPost]
        public IActionResult CreateCompany(int id, string compnayName, string details, string moto, string shortname, int multiCompanyFlag , IFormFile logo )
        {
            var fileName = Path.GetFileName(logo.FileName);
            var fileExt = Path.GetExtension(logo.FileName);
            //var rootDir = Path.Combine(_env.WebRootPath, "images");
            if (!Directory.Exists(_rootDir))
            {
                Directory.CreateDirectory(_rootDir);
            }
            var rootPath = Path.Combine(_rootDir, fileName);

            var company = new CompanyMst
            {
                CimId = id,
                CimName = compnayName,
                CimDetails = details,
                CimMoto = moto,
                CimShortName = shortname,
                MultiCompanyFlag = multiCompanyFlag,
                FileName = fileName,
                FileUpdateDate = DateTime.Now,
                FileMimeType = fileExt,
                FileCharacter = null
            };

            if (logo.Length>0)
            {
                using (var stream = new FileStream(rootPath, FileMode.Create))//File.Create(filePath, fileSize))
                {
                    logo.CopyTo(stream);
                }
            }

            var result = _company.CreateCompany(company);
            if (result==0)
            {
                return View();
            }
            return RedirectToAction(nameof(Index));
        }


        //public IActionResult EditCompany()
        //{
        //    var company = _company.GetCompany();
        //    var hrCompany = new CompanyMst()
        //    {
        //        CimId = company.CimId,
        //        CimName = company.CimName,
        //        CimDetails = company.CimDetails,
        //        CimShortName = company.CimShortName,
        //        CimMoto = company.CimMoto,
        //        FileName = company.FileName,
        //        FileMimeType = company.FileMimeType
        //    };

        //    hrCompany.CompanyDtlList.Add(new CompanyDtl() { CidId = 1 });

        //    return View(hrCompany);
        //}

        //[HttpPost]
        //public IActionResult EditCompany(CompanyMst company)
        //{
        //    if (company!=null)
        //    {


        //        HrCompany hrCompany = new HrCompany()
        //        {
        //            CimId = company.CimId,
        //            CimName = company.CimName,
        //            CimDetails = company.CimDetails,
        //            CimShortName = company.CimShortName,
        //            CimMoto = company.CimMoto,
        //            // FileName = fileName,
        //            // FileMymeType = fileExt,
        //            FileUpdateDate = DateTime.Now
        //        };

        //        if (company.Logo!=null)
        //        {

        //            var fileName = Path.GetFileName(company.Logo.FileName);
        //            var fileExt = Path.GetExtension(company.Logo.FileName);
        //            if (company.Logo.Length > 0)
        //            {
        //                var filePath = Path.Combine(_rootDir, company.FileName);
        //                FileInfo fileInfo = new FileInfo(filePath);
        //                if (fileInfo.Exists)
        //                {
        //                    fileInfo.Delete();
        //                }

        //                //var rootDir = Path.Combine(_env.WebRootPath, "images");
        //                if (!Directory.Exists(_rootDir))
        //                {
        //                    Directory.CreateDirectory(_rootDir);
        //                }
        //                var rootPath = Path.Combine(_rootDir, fileName);


        //                if (company.Logo.Length > 0)
        //                {
        //                    using (var stream = new FileStream(rootPath, FileMode.Create))//File.Create(filePath, fileSize))
        //                    {
        //                        company.Logo.CopyTo(stream);
        //                    }
        //                }

        //            }

        //            company.FileName = fileName;
        //            company.FileMimeType = fileExt;

        //            hrCompany.FileName = fileName;
        //            hrCompany.FileMymeType = fileExt;

        //        }



        //        var result = _company.EditCompanyInfo(hrCompany);
        //        if (result==1)
        //        {
        //            return RedirectToAction(nameof(Index));
        //        }
        //        else
        //        {
        //            return View();
        //        }
        //    }
        //    else
        //    {
        //        return View();
        //    }

        //}
    }
}

TerrainHRM/Views/Company/CreateCompany.cshtml
@model TerrainHRM.Models.HrCompany


@{
    ViewData["Title"] = "Company Information";
    Layout = "~/Views/Shared/_Layout.cshtml";



}

<form action="/Company/CreateCompany" method="post" enctype="multipart/form-data">
    <div class="form-group row">
        <div class="col-2 text-right">
            <label class="text-info">Company Id</label>
        </div>
        <div class="col-4">
            @*<input class="form-control" asp-for="@Model.CimId" />*@
            <input type="number" name="id" placeholder="1,2,3" autocomplete="off" />
        </div>
    </div>
    <div class="form-group row">
        <div class="col-2 text-right">
            <label class="text-info">Company Name</label>
        </div>
        <div class="col-4">
            <input type="text" name="compnayName" autocomplete="off" />
        </div>
        <div class="col-2 text-right">
            <label class="text-info">Short Name</label>
        </div>
        <div class="col-4">
            <input type="text" name="shortName" autocomplete="off" />
        </div>
    </div>
    <div class="form-group row">
        <div class="col-2 text-right">
            <label class="text-info">Company Address</label>
        </div>
        <div class="col-4">
            <input type="text" name="details" autocomplete="off" />
        </div>
        <div class="col-2 text-right">
            <label class="text-info">Company Moto</label>
        </div>
        <div class="col-4">
            <input type="text" name="moto" autocomplete="off" />
        </div>
    </div>


    <div class="form-group row">
        <div class="col-2">

        </div>
        <div class="col-4">
            <input class="form-check-input" type="checkbox" id="gridCheck">
            <label class="form-check-label" for="gridCheck">
                Multi Company Flag
            </label>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-2 text-right">
            <label class="text-info">Logo</label>
        </div>
        <div class="col-4">
            @*<input class="form-control" asp-for="@Model.CimLogoApps" />*@
            <input type="file" name="logo" required />
        </div>
    </div>

    <div class="form-group row">
        <input type="submit" class="btn btn-primary" value="Submit" />

        <a style="margin-left:10px;" class="btn btn-danger text-white" asp-action="Index" asp-controller="Company">Back</a>
    </div>
</form>



@*@model User

@{
    if (Model.ImageData != null)
    {
        var base64 = Convert.ToBase64String(Model.ImageData);
        var userImage = String.Format("data:image/gif;base64,{0}", base64);
        <img src="@userImage" alt="User Image" style="height: 300px">
    }
    else
    {
        <img src="..." alt="User Image" style="height: 300px">
 // Your default image is here
    }

}*@

TerrainHRM/Views/Company/EditCompany.cshtml
@model TerrainHRM.DTOs.HrCompanyDto

@{
  //  ViewData["Title"] = "Edit Company";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-11 mx-auto pt-0 p-0">
        <div class="card">
            <div class="card-header bg-success text-uppercase text-white">
                <h4> Update Company</h4>
            </div>
        </div>
        <form action="EditCompany" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="CimName" class="control-label"></label>
                        <input asp-for="CimName" class="form-control" />
                        <span asp-validation-for="CimName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="CimShortName" class="control-label"></label>
                        <input asp-for="CimShortName" class="form-control" />
                        <span asp-validation-for="CimShortName" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="CimDetails" class="control-label"></label>
                        <input asp-for="CimDetails" class="form-control" />
                        <span asp-validation-for="CimDetails" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="CimMoto" class="control-label"></label>
                        <input asp-for="CimMoto" class="form-control" />
                        <span asp-validation-for="CimMoto" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Logo" class="control-label"></label>
                        <input asp-for="Logo" class="form-control" onchange="document.getElementById('previewPhoto').src = window.URL.createObjectURL(this.files[0])"/>
                        <span asp-validation-for="Logo" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group col-4">
                    <img id="previewPhoto" src="~/images/NoImage.jpg" alt="Logo Image" 
                         width="125" height="125" style="border:1px;margin-top:20px;"/>
                </div>
            </div>
            <div class="col-md-12">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>Company Name</th>
                            <th>Short Name</th>
                            <th>Address</th>
                            <th>Moto</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.CompanyDtlList.Count; i++)
                        {
                        <tr>
                            <td>
                                @Html.EditorFor(x => x.CompanyDtlList[i].CidName, new { htmlAttributes = new { @class = "form-control" } })
                            </td>
                            <td>
                                @Html.EditorFor(x => x.CompanyDtlList[i].CidShortName, new { htmlAttributes = new { @class = "form-control" } })
                            </td>
                            <td>
                                @Html.EditorFor(x => x.CompanyDtlList[i].CidDetails, new { htmlAttributes = new { @class = "form-control" } })
                            </td>
                            <td>
                                @Html.EditorFor(x => x.CompanyDtlList[i].CidMoto, new { htmlAttributes = new { @class = "form-control" } })
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="btn-group col-12">
                <div class="col-6 form-group text-right p-2">
                    <a asp-action="Index" asp-controller="Company" class="btn btn-secondary"> &nbsp;Back &nbsp;</a>
                </div>
                <div class="col-6 form-group text-left p-2">
                    <input type="submit"  value="Update" class="btn btn-primary" />
                </div>
            </div>
        </form>

    </div>
    <input type="hidden" id="hdnLastIndex" value="0" />
</div>


<script>
    function addItem(btn) {
        var table = document.getElementById("company-table");
        var rows = table.getElementsByTagName("tr");
        var rowOuterHtml = rows[rows.length - 1].outerHTML;
        var newRow = table.insertRow();

        var lastRowIndex = document.getElementById("hdnLastIndex").value;
        var nextRowIndex = eval(lastRowIndex) + 1;
        document.getElementById("hdnLastIndex").value = nextRowIndex;

        rowOuterHtml = rowOuterHtml.replaceAll('_' + lastRowIndex + '_', '_' + nextRowIndex + '_');
        rowOuterHtml = rowOuterHtml.replaceAll('[' + lastRowIndex + ']', '[' + nextRowIndex + ']');
        rowOuterHtml = rowOuterHtml.replaceAll('-' + lastRowIndex, '-' + nextRowIndex);

        newRow.innerHTML = rowOuterHtml;

        var btnAddId = btn.id;
        var btnDeleteId = btnAddId.replaceAll('btnadd', 'btnremove');

        var delButtonId = document.getElementById(btnDeleteId);
        delButtonId.classList.add('visible');
        delButtonId.classList.remove('invisible');

        //var addButtonId = document.getElementById()

        //console.log(newRow);
    }
</script>

TerrainHRM/Views/Company/EditCompanyOld.cshtml
@model TerrainHRM.Models.HrCompany


@{
    ViewData["Title"] = "Company Information";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<form asp-action="EditCompany" asp-controller="Company" method="post" enctype="multipart/form-data">
    <!--action="/Company/EditCompany"-->

    <input type="hidden" asp-for="@Model.CimId" />
    <div class="form-group row">
        <div class="col-2 text-right">
            <label class="text-info">Company Name</label>
        </div>
        <div class="col-4">
            <input type="text" @*name="compnayName"*@ asp-for="@Model.CimName" class="form-control"/>
        </div>
        <div class="col-2 text-right">
            <label class="text-info">Short Name</label>
        </div>
        <div class="col-4">
            <input type="text" @*name="shortName"*@ asp-for="@Model.CimShortName" class="form-control" />
        </div>
    </div>
    <div class="form-group row">
        <div class="col-2 text-right">
            <label class="text-info">Company Address</label>
        </div>
        <div class="col-4">
            <input type="text" @*name="details"*@ asp-for="@Model.CimDetails" class="form-control" />
        </div>
        <div class="col-2 text-right">
            <label class="text-info">Company Moto</label>
        </div>
        <div class="col-4">
            <input type="text" @*name="moto"*@ asp-for="@Model.CimMoto" class="form-control" />
        </div>
    </div>


    @*<div class="form-group row">
            <div class="col-2">

            </div>
            <div class="col-4">
                <input class="form-check-input" type="checkbox" id="gridCheck" asp-for="@Model.MultiCompanyFlag">
                <label class="form-check-label" for="gridCheck">
                    Multi Company Flag
                </label>
            </div>
        </div>*@
    <div class="form-group row">
        <div class="col-2 text-right">
            <label class="text-info">Logo</label>
        </div>
        <div class="col-4">
            @*<input class="form-control" asp-for="@Model.CimLogoApps" />*@
            <input type="file" name="logo" required />
        </div>
    </div>

    <div class="form-group row">
        <input type="submit" class="btn btn-primary" value="Update" />

        <a style="margin-left:10px;" class="btn btn-danger text-white" asp-action="Index" asp-controller="Company">Back</a>
    </div>
</form>

TerrainHRM/Views/Company/Index.cshtml
@model TerrainHRM.Models.HrCompany


@{
    ViewData["Title"] = "Company Information";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var imgSrc = "~/images/" + ViewBag.ImagePath;

}

<div class="text-info row">
    <div class="text-info col-6">
        <h4>Company Information</h4>
    </div>
    <div class="text-info col-6 text-right">
        @if (Model == null)
        {
            <a class="btn btn-primary" asp-action="CreateCompany" asp-controller="Company">Create New</a>
        }
        else
        {
            <a class="btn btn-primary" asp-action="EditCompany" asp-controller="Company">Edit Company Information</a>
        }
    </div>
</div>
<hr />

<div class="row">
    <div class="col-md-6">
        @if (Model == null)
        {
            <p>No Data Found.</p>
        }
        else
        {
            <div class="form-group row">
                <div class="col-md-12 text-right">

                    <div class="form-group row" style="display:none">
                        <div class="col-2 text-right">
                            <label class="text-info">Company Id</label>
                        </div>
                        <div class="col-4">
                            @*<input class="form-control" asp-for="@Model.CimId" />*@
                            <input readonly type="text" name="id" placeholder="1,2,3" autocomplete="off" value="@Model.CimId" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2 text-right">
                            <label class="text-md-left" style="width:inherit;">Name</label>
                        </div>
                        <input readonly type="text" name="compnayName" autocomplete="off" value="@Model.CimName" class="col-md-4" />

                        <div class="col-md-2 text-right">
                            <label class="text-md-left"  style="width:inherit;">Short Name</label>
                        </div>

                        <input readonly value="@Model.CimShortName" type="text" name="shortName" autocomplete="off" class="col-md-4" />
                    </div>
                    <div class="form-group row">
                        <div class="col-2 text-right">
                            <label class="text-md-left"  style="width:inherit;">Address</label>
                        </div>
                            <input readonly value="@Model.CimDetails" type="text" name="details" autocomplete="off" class="col-md-4" />
                        <div class="col-2 text-right">
                            <label class="text-md-left"  style="width:inherit;">Moto</label>
                        </div>
                            <input readonly value="@Model.CimMoto" type="text" name="moto" autocomplete="off" class="col-md-4" />
                    </div>
                </div>
            </div>

            <div class="col-4">
                <img src="@imgSrc" height="250" width="250" asp-append-version="true" />
            </div>


        }

    </div>

    <div class="col-md-6">

    </div>

</div>