TerrainHRM/Controllers/ApplicantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TerrainHRM.Helper;
using TerrainHRM.Interfaces;
using TerrainHRM.Models;

namespace TerrainHRM.Controllers
{
    public class ApplicantController : Controller
    {
        private readonly IApplicantRepository _applicant;

        public ApplicantController(IApplicantRepository applicant)
        {
            _applicant = applicant;
        }
        public IActionResult Index()
        {
            List<HrApplicantOld> applicants = _applicant.GetAllApplicants();
            return View(applicants);
        }

        public IActionResult ApplicantDetails(int id)
        {
            HrApplicantOld applicant = _applicant.GetApplicant(id);
            return View(applicant);            
        }

        [HttpGet]
        public IActionResult CreateApplicant()
        {
            HrApplicantOld applicant = new HrApplicantOld();
            applicant.HrExperiences.Add(new HrExperiences { ExperienceId = 1 });
            applicant.HrExperiences.Add(new HrExperiences { ExperienceId = 2 });
            applicant.HrExperiences.Add(new HrExperiences { ExperienceId = 3 });
            return View(applicant);
        }

        [HttpPost]
        public IActionResult CreateApplicant(HrApplicantOld applicant)
        {
            applicant.ApplicantId = DbConnectionHelper.GetMaxPKValue("HR_APPLICANT", "APPLICANT_ID")+1;
            var expId = DbConnectionHelper.GetMaxPKValue("HR_EXPERIENCE", "EXPERIENCE_ID") + 1;

            foreach (var item in applicant.HrExperiences)
            {
                item.ExperienceId = expId;
                expId++;
            }

            var result = _applicant.InsertApplicant(applicant);
            if (result==0)
            {
                return View(applicant);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

TerrainHRM/Views/Applicant/ApplicantDetails.cshtml
@model TerrainHRM.Models.HrApplicantOld

@{
    ViewData["Title"] = "Applicant Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-6 text-left">
        <h4>Applicant Details</h4>
    </div>
    <div class="col-6 text-right">
        <a asp-controller="Applicant" asp-action="Index" class="btn btn-primary">Back to Applicant List</a>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-2">

    </div>
    <div class="col-8">
        <div class="form-group row">

            <div class="col-2 text-left">
                <label class="text-dark">Name</label>
            </div>
            <div class="col-4">
                <input class="text-center font-weight-bold" readonly type="text" name="Name" value="@Model.Name" />
            </div>
            <div class="col-2 text-left">
                <label class="text-dark">Gender</label>
            </div>
            <div class="col-4 text-center font-weight-bold">
                <input class="text-center font-weight-bold" readonly value="@Model.Gender" type="text" name="Gender" />
            </div>

        </div>

        <div class="form-group row">
            <div class="col-2 text-left">
                <label class="text-dark">Age</label>
            </div>
            <div class="col-4 text-center font-weight-bold">
                <input class="text-center font-weight-bold" readonly type="text" name="Age" value="@Model.Age" />
            </div>
            <div class="col-2 text-left">
                <label class="text-dark">Total Experience</label>
            </div>
            <div class="col-4 text-center font-weight-bold">
                <input class="text-center font-weight-bold" readonly value="@Model.TotalExperiences" type="text" name="TotalExperiences" />
            </div>
        </div>
    </div>
    <div class="col-2">

    </div>
</div>

<table class="table table-bordered col-8 table-sm mx-auto">
    <thead class="thead-dark">
        <tr>
            <th class="text-center">Company Name</th>
            <th class="text-center">Designation</th>
            <th class="text-center">Years Worked</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var exp in Model.HrExperiences)
        {
            <tr>
                <td class="text-center">@exp.CompanyName</td>
                <td class="text-center">@exp.Designation</td>
                <td class="text-center">@exp.YearsWorked</td>
            </tr>
        }
    </tbody>
</table>

TerrainHRM/Views/Applicant/CreateApplicant.cshtml
@model TerrainHRM.Models.HrApplicantOld

@{ 
    ViewData["Title"] = "Create Applicant";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Create Applicant</h4>
<hr />
<div class="row">
    <form action="CreateApplicant" method="post">

            <div class="form-group row">

                <div class="col-md-2 text-left">
                    <label class="text-dark">Name</label>
                </div>
                <div class="col-md-4">
                    <input class="form-control" asp-for="Name" />
                </div>
                <div class="col-md-2 text-left">
                    <label class="text-dark">Gender</label>
                </div>
                <div class="col-md-4">
                    <input class="form-control" asp-for="Gender" />
                </div>

            </div>

            <div class="form-group row">
                <div class="col-md-2 text-left">
                    <label class="text-dark">Age</label>
                </div>
                <div class="col-md-4">
                    <input class="form-control" asp-for="Age" />
                </div>
                <div class="col-md-2 text-left">
                    <label class="text-dark">Total Experience</label>
                </div>
                <div class="col-md-4">
                    <input class="form-control" asp-for="TotalExperiences" />
                </div>
            </div>

            <table>
                <thead class="thead-dark">
                    <tr>
                        <th>Company Name</th>
                        <th>Designation</th>
                        <th>Years Worked</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.HrExperiences.Count; i++)
                    {
                    <tr>
                        <td>
                            @Html.EditorFor(x => x.HrExperiences[i].CompanyName, new { htmlAttribute = new { @class = "form-control" } })
                        </td>
                        <td>
                            @Html.EditorFor(x => x.HrExperiences[i].Designation, new { htmlAttribute = new { @class = "form-control" } })
                        </td>
                        <td>
                            @Html.EditorFor(x => x.HrExperiences[i].YearsWorked, new { htmlAttribute = new { @class = "form-control" } })
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
            <br />
            <div class="form-group row">
                <div class="col-8">

                </div>
                <input type="submit" value="Submit" class="btn btn-primary" />
                <a class="btn btn-warning" asp-action="Index" asp-controller="Applicant">Back</a>
            </div>

    </form>
</div>

TerrainHRM/Views/Applicant/Index.cshtml
@model IEnumerable<TerrainHRM.Models.HrApplicantOld>

@{ 
    ViewData["Title"] = "Applicant List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-6 text-left">
        <h4>Applicant List</h4>
    </div>
    <div class="col-6 text-right">
        <a class="btn btn-primary" asp-controller="Applicant" asp-action="CreateApplicant">Create Applicant</a>
    </div>
</div>
<hr />
@if (Model.Count() == 0)
{
    <p>No Data Found.</p>
}
else
{
    <table class="table table-bordered col-8 table-sm mx-auto">
        <thead class="thead-dark">
            <tr>
                <th  class="text-center">#</th>
                <th class="text-center">Applicant Name</th>
                <th class="text-center">Gender</th>
                <th class="text-center">Age</th>
                <th class="text-center">Total Experiences</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var applicant in Model)
            {
                <tr>                    
                    <td class="text-center"><a asp-controller="Applicant" asp-action="ApplicantDetails" asp-route-id="@applicant.ApplicantId"><i class="fas fa-edit"></i></a></td>
                    <td class="text-center">@applicant.Name</td>
                    <td class="text-center">@applicant.Gender</td>
                    <td class="text-center">@applicant.Age</td>
                    <td class="text-center">@applicant.TotalExperiences</td>
                </tr>
            }
        </tbody>
    </table>
}